"""Initial schema

Revision ID: 3ce720f66400
Revises:
Create Date: 2026-07-04 14:28:12.710384

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '3ce720f66400'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gap_clusters',
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('cluster_title', sa.String(), nullable=False),
    sa.Column('cluster_summary', sa.String(), nullable=False),
    sa.Column('gap_category', sa.String(), nullable=False),
    sa.Column('evidence_score', sa.Float(), nullable=False),
    sa.Column('confidence_level', sa.String(), nullable=False),
    sa.Column('gap_object_count', sa.Integer(), nullable=False),
    sa.Column('paper_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cluster_id')
    )
    op.create_index(op.f('ix_gap_clusters_cluster_id'), 'gap_clusters', ['cluster_id'], unique=False)
    op.create_table('papers',
    sa.Column('pmid', sa.String(), nullable=False),
    sa.Column('pmcid', sa.String(), nullable=True),
    sa.Column('doi', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('journal', sa.String(), nullable=True),
    sa.Column('publication_year', sa.Integer(), nullable=True),
    sa.Column('study_type', sa.String(), nullable=True),
    sa.Column('mesh_terms', sa.JSON(), nullable=True),
    sa.Column('authors', sa.JSON(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=True),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pmid')
    )
    op.create_index(op.f('ix_papers_doi'), 'papers', ['doi'], unique=False)
    op.create_index(op.f('ix_papers_pmcid'), 'papers', ['pmcid'], unique=False)
    op.create_index(op.f('ix_papers_pmid'), 'papers', ['pmid'], unique=False)
    op.create_table('report_cache',
    sa.Column('cache_id', sa.String(), nullable=False),
    sa.Column('normalized_topic', sa.String(), nullable=False),
    sa.Column('paper_limit', sa.Integer(), nullable=False),
    sa.Column('generated_report', sa.JSON(), nullable=False),
    sa.Column('cluster_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('cache_id')
    )
    op.create_index(op.f('ix_report_cache_cache_id'), 'report_cache', ['cache_id'], unique=False)
    op.create_index(op.f('ix_report_cache_normalized_topic'), 'report_cache', ['normalized_topic'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('security_key_hash', sa.String(), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('credit_ledger',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('feature', sa.String(), nullable=False),
    sa.Column('credits_before', sa.Integer(), nullable=False),
    sa.Column('credits_deducted', sa.Integer(), nullable=False),
    sa.Column('credits_after', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_ledger_id'), 'credit_ledger', ['id'], unique=False)
    op.create_table('deep_explore_jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('requested_topic', sa.String(), nullable=False),
    sa.Column('normalized_topic', sa.String(), nullable=False),
    sa.Column('paper_limit', sa.Integer(), nullable=False),
    sa.Column('credits_used', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('execution_time', sa.Integer(), nullable=True),
    sa.Column('report_cache_id', sa.String(), nullable=True),
    sa.Column('search_queries', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_deep_explore_jobs_job_id'), 'deep_explore_jobs', ['job_id'], unique=False)
    op.create_table('gap_objects',
    sa.Column('gap_object_id', sa.String(), nullable=False),
    sa.Column('pmid', sa.String(), nullable=False),
    sa.Column('pmcid', sa.String(), nullable=True),
    sa.Column('gap_category', sa.String(), nullable=False),
    sa.Column('gap_statement', sa.String(), nullable=False),
    sa.Column('supporting_evidence', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('suggested_study', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.Vector(768), nullable=True),
    sa.ForeignKeyConstraint(['pmid'], ['papers.pmid'], ),
    sa.PrimaryKeyConstraint('gap_object_id')
    )
    op.create_index(op.f('ix_gap_objects_confidence'), 'gap_objects', ['confidence'], unique=False)
    op.create_index(op.f('ix_gap_objects_gap_category'), 'gap_objects', ['gap_category'], unique=False)
    op.create_index(op.f('ix_gap_objects_gap_object_id'), 'gap_objects', ['gap_object_id'], unique=False)
    op.create_index(op.f('ix_gap_objects_pmid'), 'gap_objects', ['pmid'], unique=False)
    op.create_table('gap_cluster_mapping',
    sa.Column('cluster_id', sa.String(), nullable=False),
    sa.Column('gap_object_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['gap_clusters.cluster_id'], ),
    sa.ForeignKeyConstraint(['gap_object_id'], ['gap_objects.gap_object_id'], ),
    sa.PrimaryKeyConstraint('cluster_id', 'gap_object_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('gap_cluster_mapping')
    op.drop_index(op.f('ix_gap_objects_pmid'), table_name='gap_objects')
    op.drop_index(op.f('ix_gap_objects_gap_object_id'), table_name='gap_objects')
    op.drop_index(op.f('ix_gap_objects_gap_category'), table_name='gap_objects')
    op.drop_index(op.f('ix_gap_objects_confidence'), table_name='gap_objects')
    op.drop_table('gap_objects')
    op.drop_index(op.f('ix_deep_explore_jobs_job_id'), table_name='deep_explore_jobs')
    op.drop_table('deep_explore_jobs')
    op.drop_index(op.f('ix_credit_ledger_id'), table_name='credit_ledger')
    op.drop_table('credit_ledger')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_report_cache_normalized_topic'), table_name='report_cache')
    op.drop_index(op.f('ix_report_cache_cache_id'), table_name='report_cache')
    op.drop_table('report_cache')
    op.drop_index(op.f('ix_papers_pmid'), table_name='papers')
    op.drop_index(op.f('ix_papers_pmcid'), table_name='papers')
    op.drop_index(op.f('ix_papers_doi'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_gap_clusters_cluster_id'), table_name='gap_clusters')
    op.drop_table('gap_clusters')
    # ### end Alembic commands ###
